name: CI
on: [push, pull_request]
env:
  HTTPTOOLKIT_SERVER_DISABLE_AUTOUPDATE: 1 # Don't try to autoupdate during tests etc
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-22.04
    container:
      image: httptoolkit/act-build-base:v3.0.0
      options: "--privileged" # Required for DIND tests
    env:
      DIND_HOST: unix:///tmp/docker.sock
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20.8.0

      - run: npm install -g npm@^8

      - run: npm ci
        env:
          NPM_CONFIG_UNSAFE_PERM: true

      - run: npm run build:src

      - run: npm run build:release
        env:
          SENTRY_AUTH_TOKEN: ${{ (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && secrets.SENTRY_AUTH_TOKEN) || '' }}
          SENTRY_ORG: http-toolkit
          SENTRY_PROJECT: httptoolkit-server
          NPM_CONFIG_UNSAFE_PERM: true

      - uses: actions/upload-artifact@v3
        with:
          name: distributables
          path: build/dist/*
          if-no-files-found: error
